run_config:
  print_time: False
  device: cuda
  dataset: adult
  max_epoch: 1000
  learning_rate: 0.001
  batch_size: 128
  batch_size_test: 12
  K: 100
  num_layers: 1
  embedding_dim: 128
  propagation_steps: 1
  unseen_rate: 0
  aug_strategy: "random"
  N_BINS: 100
  random_state: 42
  evaluate_stride: 10

wandb_config:
  use_wandb: False
  entity: tabhyperformer
  project: K_fold test 0727 
  name : v9.3 1000123
  group: v9.3 1000123
  notes: V10

