run_config:
  log_name: test
  print_time: False
  device: cuda
  dataset: eye_movements_num
  metric: binary_AUC
  # 'binary_AUC', 'ACC'
  max_epoch: 5
  learning_rate: 0.001
  batch_size: 128
  batch_size_test: 12
  K: 100
  num_layers: 1
  embedding_dim: 128
  propagation_steps: 1
  unseen_rate: 0
  aug_strategy: "random"
  N_BINS: 100
  random_state: 42
  evaluate_stride: 1
wandb_config:
  use_wandb: False
  entity: tabhyperformer
  project: new test
  name : V10.9 compas K1000 N100
  group: V10.9 change infer C_input
  notes: V10.9
tensorboard_config:
  use_tensorboard: False
  name: test
logger_config:
  use_logger: True
  dump_log: True
  plot_log: True
