run_config:
  log_name: test
  print_time: False
  device: cuda
  dataset: adult
  metric: ACC
  # 'binary_AUC', 'ACC'
  max_epoch: 200
  learning_rate: 0.001
  batch_size: 128
  batch_size_test: 24
  K: 100
  num_layers: 1
  embedding_dim: 128
  propagation_steps: 1
  unseen_rate: 0.0
  aug_strategy: "unseen"
  N_BINS: 100
  random_state: 42
  evaluate_stride: 1
wandb_config:
  use_wandb: False
  entity: a220284268
  project: TABHGNN
  name : run
  group: compas_N500K500
  notes: V11
tensorboard_config:
  use_tensorboard: False
  name: test
logger_config:
  use_logger: False
  dump_log: True
  plot_log: True
